### ISSUE TITLE
Nest assignment is ignored smd['some-key']['x']

### ISSUE THREAD

**Issue by marcelomanzo** [luizalabs/shared-memory-dict#58]
from shared_memory_dict import SharedMemoryDict
smd = SharedMemoryDict(name='tokens', size=1024)
smd['some-key'] = {}
smd['some-key']['x'] = 1 #this statement is ignored
print(smd) #output {'some-key': {}}

**Comment by druidance** [comment]
Was baffled by this limitation as well. 

As a work around, how about juggling the nested object?
```
from shared_memory_dict import SharedMemoryDict

smd = SharedMemoryDict(name='tokens', size=1024)

temp = smd['some-key'] = {}
temp['x'] = 1
smd['some-key'] = temp
print(smd) #output {'some-key': {'x': 1}}
```
edit: added more comments

**Comment by githubdontbanmeagain** [comment]
Is there a better fix for this? The "juggling" above throws an error.

**Comment by druidance** [comment]
> Is there a better fix for this? The "juggling" above throws an error.

Hey,

Could you show the error you're getting there?

**Comment by githubdontbanmeagain** [comment]
client is a initialized class, key is a str

```py
smd = SharedMemoryDict(name="123", size=1024)
smd["data"]

def add_to_data():
    temp = smd["data"]
    temp[key] = {
            "key": key,
            "client": client,
    }
    smd["data"] = temp

def add_to_data()
```


```
Traceback (most recent call last):
  File "C:\Users\x\x.py", line 34, in x
    smd"data"] = temp
  File "C:\Users\x\AppData\Local\Programs\Python\Python39\lib\site-packages\shared_memory_dict\dict.py", line 96, in __setitem__
    db[key] = value
  File "C:\Users\x\AppData\Local\Programs\Python\Python39\lib\contextlib.py", line 124, in __exit__
    next(self.gen)
  File "C:\Users\x\AppData\Local\Programs\Python\Python39\lib\site-packages\shared_memory_dict\dict.py", line 89, in _modify_db
    self._save_memory(db)
  File "C:\Users\x\AppData\Local\Programs\Python\Python39\lib\site-packages\shared_memory_dict\dict.py", line 177, in _save_memory
    data = self._serializer.dumps(db)
  File "C:\Users\x\AppData\Local\Programs\Python\Python39\lib\site-packages\shared_memory_dict\serializers.py", line 44, in dumps
    return pickle.dumps(obj, pickle.HIGHEST_PROTOCOL)
AttributeError: Can't pickle local object 'WeakValueDictionary.__init__.<locals>.remove'
```

**Comment by githubdontbanmeagain** [comment]
I tested it without client, that seems to be the issue. I'm not quite sure how to go about this

**Comment by githubdontbanmeagain** [comment]
Got this error when using the built in JSONSerializer instead, as I read pickle has problems with local objects:

```
  File "C:\Users\x\AppData\Local\Programs\Python\Python39\lib\site-packages\shared_memory_dict\serializers.py", line 31, in dumps
    raise SerializationError(obj)
shared_memory_dict.serializers.SerializationError: Failed to serialize data: {...
```

**Comment by druidance** [comment]
> client is a initialized class, key is a str

I think this is the problem you've got there as it relates to the fact that you cannot assign custom objects (that cannot be pickled) as values. Change your _client_ type to something more common - such as _str_ or _int_ - and you'll get the result.
```
from shared_memory_dict import SharedMemoryDict

smd = SharedMemoryDict(name="123", size=1024)
smd["data"] = {}


def add_to_data(key, client):
    temp = smd["data"]
    temp[key] = {
            "key": key,
            "client": client,
    }
    smd["data"] = temp

key = 1
client = 'Client'
add_to_data(key, client)
```
What is the reason for passing such _client_ object between the processes? Does it hold some kind of important information you want to update?

**Comment by githubdontbanmeagain** [comment]
Yes, the client class has functions and data that I need to access in other files. So simply using a string would not really work..

I tried using dill (a drop in replacement for pickle with more support for custom types), but I face different issues there.

I could store the clients in a local dict in that file, and then send read/write commands through shared memory, but that would really be pain, I'm trying to find a clean solution.

**Comment by druidance** [comment]
How about refactoring class data out to DTOs that can be passed around through the _SharedMemoryDict_ functionality? 

I think that was the core concept behind [shared_memory](https://docs.python.org/3/library/multiprocessing.shared_memory.html) objects.

**Comment by githubdontbanmeagain** [comment]
That would kinda be a little complex, the functions need the context of the client class to work properly, as there are multiple clients initialized

**Comment by druidance** [comment]
Sorry, but I'm afraid I cannot help any further since I do not possess enough information about the logic you're trying to implement. It seems to be out of _SharedMemoryDict_ scope.

**Comment by githubdontbanmeagain** [comment]
All good, it's an issue with pickle/dill.
